import { lstat, readFile, readdir } from "node:fs/promises";
import { extname, isAbsolute, join, relative, sep } from "node:path";

export function isWithin(parent: string, child: string): boolean {
  const path = relative(parent, child);
  return path === "" || (!isAbsolute(path) && path !== ".." && !path.startsWith(`..${sep}`));
}

export async function listFiles(root: string): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  async function visit(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);
      if (entry.isSymbolicLink()) {
        throw new Error(`Refusing to use a generated directory containing a symlink: ${path}`);
      }
      if (entry.isDirectory()) {
        await visit(path);
      } else if (entry.isFile()) {
        files.set(relative(root, path).split(sep).join("/"), await readFile(path, "utf8"));
      } else {
        throw new Error(`Unexpected file in generated directory: ${path}`);
      }
    }
  }
  await visit(root);
  return files;
}

export function hasErrorCode(error: unknown, code: string): boolean {
  return error instanceof Error && "code" in error && error.code === code;
}

export async function outputFiles(output: string): Promise<Map<string, string>> {
  let stats;
  try {
    stats = await lstat(output);
  } catch (error) {
    if (hasErrorCode(error, "ENOENT")) {
      return new Map();
    }
    throw error;
  }
  if (!stats.isDirectory() || stats.isSymbolicLink()) {
    throw new Error(`Output must be a regular directory: ${output}`);
  }
  const files = await listFiles(output);
  for (const [name, source] of files) {
    if (
      extname(name) !== ".ts" ||
      !/^\/\*\*\r?\n \* Generated by (?:orval|lit-query-codegen)\r?\n/.test(source)
    ) {
      throw new Error(
        `Refusing to replace a file not owned by the generator: ${join(output, name)}`,
      );
    }
  }
  return files;
}
