import { mkdir, mkdtemp, readFile, rename, rm, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, parse, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { generate as generateOrval } from "orval";
import * as prettier from "prettier";
import type { OpenAPIV3 } from "@scalar/openapi-types";
import type { CodegenConfig, FeatureOptions, GenerateOptions, GenerateResult } from "./config.js";
import { renderApi } from "./render-api.js";
import { renderQueryFiles } from "./render-queries.js";
import { collectOperations, identifier, operationName } from "./openapi.js";
import { hasErrorCode, isWithin, listFiles, outputFiles } from "./files.js";

const runtimeSource = fileURLToPath(new URL("../src/runtime.ts", import.meta.url));

function importPath(fromDirectory: string, target: string): string {
  let path = relative(fromDirectory, target).split(sep).join("/");
  path = path.replace(/\.(?:[cm]?ts|[cm]?js)$/, "");
  return path.startsWith(".") ? path : `./${path}`;
}

function featureImports(feature: FeatureOptions, featureDir: string, cwd: string): string[] {
  return (feature.imports ?? []).map(({ from, names }) => {
    const module =
      from.startsWith(".") || isAbsolute(from) ? importPath(featureDir, resolve(cwd, from)) : from;
    if (!names.length) {
      throw new Error(`Feature import needs at least one name: ${from}`);
    }
    return `import { ${names.map((name) => identifier(name, "import name")).join(", ")} } from ${JSON.stringify(module)};`;
  });
}

export async function generate(
  config: CodegenConfig,
  options: GenerateOptions = {},
): Promise<GenerateResult> {
  if (!config || typeof config.input !== "string" || typeof config.output !== "string") {
    throw new Error("Configuration requires input and output paths");
  }
  const cwd = resolve(options.cwd ?? process.cwd());
  const workspace = resolve(cwd, config.workspace ?? ".");
  const input = resolve(cwd, config.input);
  const output = resolve(cwd, config.output);
  const requestPath = config.request ? resolve(cwd, config.request.path) : runtimeSource;
  if (
    output === parse(output).root ||
    isWithin(output, cwd) ||
    isWithin(output, input) ||
    isWithin(output, requestPath)
  ) {
    throw new Error(`Output must be a dedicated generated directory: ${output}`);
  }
  const existing = await outputFiles(output);
  const spec = JSON.parse(await readFile(input, "utf8")) as OpenAPIV3.Document;
  if (!spec || !/^3\./.test(spec.openapi ?? "") || !spec.info || !spec.paths) {
    throw new Error("Input must be an OpenAPI 3 JSON document with info and paths");
  }
  const { operationsByTag, mutationOperations } = collectOperations(spec, config);
  const tags = [...operationsByTag.keys()].sort();
  const namespaces = new Set();
  for (const tag of tags) {
    const namespace = identifier(
      tag.replace(/-([a-z0-9])/g, (_, character) => character.toUpperCase()),
      "feature namespace",
    );
    if (namespaces.has(namespace)) {
      throw new Error(`Duplicate feature namespace: ${namespace}`);
    }
    namespaces.add(namespace);
  }
  const header = [
    "/**",
    " * Generated by orval",
    " * Do not edit manually.",
    ` * ${String(spec.info.title).replace(/\*\//g, "* /")}`,
    ` * OpenAPI spec version: ${String(spec.info.version).replace(/\*\//g, "* /")}`,
    " */",
  ].join("\n");
  const prettierOptions = {
    ...(await prettier.resolveConfig(join(cwd, "lit-query-codegen.config.ts"))),
    ...config.prettier,
    parser: "typescript",
  };
  const format = (source: string) => prettier.format(source, prettierOptions);
  await mkdir(dirname(output), { recursive: true });
  const temp = await mkdtemp(join(dirname(output), `.${basename(output)}.lit-query-codegen-`));
  const staged = join(temp, "generated");
  await mkdir(staged);
  let cleanup = true;
  try {
    for (const tag of tags) {
      const featureDir = join(staged, tag);
      const finalFeatureDir = join(output, tag);
      const requestImport = config.request
        ? importPath(finalFeatureDir, requestPath)
        : "lit-query-codegen/runtime";
      const operations = operationsByTag.get(tag)!;
      const feature = config.features?.[tag] ?? {};
      const imports = featureImports(feature, finalFeatureDir, cwd);
      await generateOrval(
        {
          input: { target: input, filters: { tags: [tag] } },
          output: {
            mode: "split",
            target: join(featureDir, "api.ts"),
            schemas: false,
            client: "fetch",
            override: {
              mutator: { path: requestPath, name: "apiFetch" },
              fetch: { includeHttpResponseReturnType: false, forceSuccessResponse: true },
            },
          },
        },
        workspace,
        { throwOnError: true, logLevel: "error" },
      );
      const apiSource = renderApi(
        await readFile(join(featureDir, "api.ts"), "utf8"),
        operations,
        header,
        requestImport,
      );
      await writeFile(join(featureDir, "api.ts"), await format(apiSource));
      const generatedModels = join(featureDir, "api.schemas.ts");
      let modelsSource;
      try {
        modelsSource = await readFile(generatedModels, "utf8");
        modelsSource = modelsSource.replace(/^\/\*\*[\s\S]*?\*\//, header);
        await rm(generatedModels);
      } catch (error) {
        if (!hasErrorCode(error, "ENOENT")) {
          throw error;
        }
        modelsSource = `${header}\n\nexport {};\n`;
      }
      if (!/^export\s/m.test(modelsSource)) {
        modelsSource += "\nexport {};\n";
      }
      await writeFile(join(featureDir, "models.ts"), await format(modelsSource));
      const aliases = Object.fromEntries(
        Object.entries(config.queryAliases?.[tag] ?? {}).map(([alias, members]) => [
          identifier(alias, "query alias"),
          Object.fromEntries(
            Object.entries(members).map(([key, name]) => [key, operationName(name)]),
          ),
        ]),
      );
      const { queries, mutations } = renderQueryFiles(tag, operations, apiSource, header, {
        feature,
        imports,
        mutationOperations,
        aliases,
      });
      if (queries) {
        await writeFile(join(featureDir, "queries.ts"), await format(queries));
      }
      if (mutations) {
        await writeFile(join(featureDir, "mutations.ts"), await format(mutations));
      }
      const runtimeExports = config.request?.exports ?? ["ApiError"];
      const runtimeTypeExports = config.request?.typeExports ?? ["ApiProblem", "ApiRequestOptions"];
      const barrel = [
        header,
        "",
        'export * from "./api";',
        'export * from "./models";',
        ...(queries ? ['export * from "./queries";'] : []),
        ...(mutations ? ['export * from "./mutations";'] : []),
        ...(runtimeExports.length
          ? [
              `export { ${runtimeExports.map((name) => identifier(name, "request export")).join(", ")} } from ${JSON.stringify(requestImport)};`,
            ]
          : []),
        ...(runtimeTypeExports.length
          ? [
              `export type { ${runtimeTypeExports.map((name) => identifier(name, "request type export")).join(", ")} } from ${JSON.stringify(requestImport)};`,
            ]
          : []),
        "",
      ].join("\n");
      await writeFile(join(featureDir, "index.ts"), await format(barrel));
    }
    await writeFile(
      join(staged, "index.ts"),
      await format(
        `${header}\n\n${tags.map((tag) => `export * as ${tag.replace(/-([a-z0-9])/g, (_, character) => character.toUpperCase())} from "./${tag}";`).join("\n")}\n`,
      ),
    );
    const files = await listFiles(staged);
    if (options.check) {
      const changed = [...new Set([...files.keys(), ...existing.keys()])].filter(
        (name) => files.get(name) !== existing.get(name),
      );
      if (changed.length) {
        throw new Error(
          `Generated client is out of date:\n${changed.sort().join("\n")}\nRun lit-query-codegen to regenerate it.`,
        );
      }
    } else {
      // Check ownership again immediately before replacing the generated directory.
      await outputFiles(output);
      const backup = join(temp, "previous");
      let moved = false;
      try {
        await rename(output, backup);
        moved = true;
      } catch (error) {
        if (!hasErrorCode(error, "ENOENT")) {
          throw error;
        }
      }
      try {
        await rename(staged, output);
      } catch (error) {
        if (moved) {
          try {
            await rename(backup, output);
          } catch (restoreError) {
            cleanup = false;
            throw new AggregateError(
              [error, restoreError],
              `Could not replace or restore the client. Previous files are preserved at ${backup}`,
            );
          }
        }
        throw error;
      }
    }
    return { output, tags, files: [...files.keys()].sort() };
  } finally {
    // temp is the absolute, dedicated path returned by mkdtemp above.
    if (
      dirname(temp) !== dirname(output) ||
      !basename(temp).startsWith(`.${basename(output)}.lit-query-codegen-`)
    ) {
      throw new Error(`Unexpected temporary directory: ${temp}`);
    }
    if (cleanup) {
      await rm(temp, { recursive: true, force: true });
    }
  }
}
